# Generated by Django 4.2.27 on 2026-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_mean_low',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_success_high',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_uncertainty_high',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_variance_high',
            field=models.FloatField(default=0.18),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_variance_low',
            field=models.FloatField(default=0.15),
        ),
    ]
