# Generated by Django 4.2.27 on 2026-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_user_managers_test_threshold_mean_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='threshold_relative_difficulty_low',
            field=models.FloatField(default=-0.25),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_shock_index_high',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold_zero_score_high',
            field=models.FloatField(default=0.35),
        ),
    ]
