# Generated by Django 4.2.27 on 2026-06-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_test_threshold_relative_difficulty_low_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='threshold_shock_index_high',
        ),
        migrations.RemoveField(
            model_name='test',
            name='threshold_zero_score_high',
        ),
    ]
