# Generated by Django 4.2.27 on 2026-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_test_threshold_shock_index_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='threshold_mean_low',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='subject',
            name='threshold_relative_difficulty_high',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='subject',
            name='threshold_relative_difficulty_low',
            field=models.FloatField(default=-0.15),
        ),
        migrations.AddField(
            model_name='subject',
            name='threshold_success_high',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='subject',
            name='threshold_variance_high',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='subject',
            name='threshold_variance_low',
            field=models.FloatField(default=0.1),
        ),
    ]
