# Generated by Django 4.2.27 on 2026-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_threshold_mean_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='threshold_mean_low',
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold_relative_difficulty_high',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold_relative_difficulty_low',
            field=models.FloatField(default=-0.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold_success_high',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold_variance_high',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='subject',
            name='threshold_variance_low',
            field=models.FloatField(default=0.3),
        ),
    ]
